version: '3.8'

services:
  backend:
    build: .
    container_name: ecom-backend
    ports:
      - '4000:4000'
      - '5555:5555'
    env_file:
      - .env
    depends_on:
      - db
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - ecom-network

  db:
    image: postgres:15
    container_name: ecom-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecom_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ecom-network

volumes:
  pgdata:

networks:
  ecom-network:
    driver: bridge
