services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ecom-backend:latest
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    container_name: ecom-backend
    ports:
      - '4000:4000'
      - '5555:5555'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@ecom-db:5432/ecom_db
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - ecom-network

  db:
    image: postgres:latest
    container_name: ecom-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecom_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ecom-network

  adminer:
    image: adminer:latest
    container_name: ecom-adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - ecom-network

volumes:
  pgdata:

networks:
  ecom-network:
    driver: bridge
