name: Deploy Production

permissions:
  contents: read
  packages: read
  pull-requests: write

on:
  push:
    branches: ['main']

jobs:
  build:
    name: Build Backend API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        run: echo "${{secrets.ENV_PRODUCTION}}" > .env
      - name: Build docker image
        run: docker build --platform linux/amd64 -t plongtran239/ecom-backend:v0 -f Dockerfile .
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push docker image
        run: docker push plongtran239/ecom-backend:v0
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          key: ${{ secrets.KEY_PRODUCTION }}
          port: ${{ secrets.PORT_PRODUCTION }}
          script: |
            cd ecommerce-deployment/
            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            export DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}
            ./scripts/deploy.sh
